### ISSUE TITLE
skeleton fails after pip install --user shutit

### ISSUE THREAD

**Issue by garthk** [ianmiell/shutit#232]
On OS X:

```
pip install --user shutit
cd /tmp
mkdir foo
cd foo
shutit skeleton
```

… and tap Enter a few times to see:

```
Traceback (most recent call last):
  File "/Users/garth/Library//Python/2.7/bin/shutit", line 11, in <module>
    sys.exit(main())
  File "/Users/garth/Library/Python/2.7/lib/python/site-packages/shutit_main.py", line 858, in main
    shutit_util.create_skeleton(shutit)
  File "/Users/garth/Library/Python/2.7/lib/python/site-packages/shutit_util.py", line 1439, in create_skeleton
    templatemodule = open(find_asset('shutit_module_template_bare.py')).read()
IOError: [Errno 2] No such file or directory: 'shutit_module_template_bare.py'
```

It's right there in `$HOME/Library/Python/2.7/shutit_assets/`, aka `os.path.abspath(os.path.join(os.path.dirname(shutit_main.__file__), '../../../shutit_assets'))`.

**Comment by ianmiell** [comment]
Thanks for raising this! Not enough people let me know about stuff like this.

I believe it works now (had to upgrade pip).

Let me know how you get on.

```sh
imiell@Ians-Air:~$ pip install --upgrade pip
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip
  Downloading pip-7.1.0-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 249kB/s 
Installing collected packages: pip
  Found existing installation: pip 7.0.3
    Uninstalling pip-7.0.3:
      Successfully uninstalled pip-7.0.3
Successfully installed pip-7.1.0
imiell@Ians-Air:~$ pip install --user shutit
Collecting shutit
  Using cached shutit-0.8.82-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): texttable>=0.1 in /usr/local/lib/python2.7/site-packages (from shutit)
Requirement already satisfied (use --upgrade to upgrade): pexpect<3.0,>=2.0 in /usr/local/lib/python2.7/site-packages (from shutit)
Requirement already satisfied (use --upgrade to upgrade): pynsca>=1.5 in /usr/local/lib/python2.7/site-packages (from shutit)
Requirement already satisfied (use --upgrade to upgrade): bottle>0.1 in /usr/local/lib/python2.7/site-packages (from shutit)
Installing collected packages: shutit
Successfully installed shutit
imiell@Ians-Air:~$ shutit skeleton

# Input a new directory name for this module.
# Default: /tmp/shutit_faffle



# Input module name.
# Default: shutit_faffle



# Input a unique domain.
# Default: imiell.shutit_faffle


cp: .gitignore: No such file or directory
================================================================================
Run:

	cd /tmp/shutit_faffle/bin && ./build.sh

to build.

An image called shutit_faffle will be created
and can be run with the run.sh command in bin/.
================================================================================
imiell@Ians-Air:~$ 
```

**Comment by ianmiell** [comment]
Assuming this is ok now, closing.

**Comment by garthk** [comment]
Not OK enough, I'm afraid:

```
$ pip --version
pip 7.1.2 …
$ pip install --user shutit
$ pip install --user shutit
Collecting shutit
  Using cached shutit-0.8.91-py2-none-any.whl
Installing collected packages: shutit
Successfully installed shutit-0.8.91
$ mkdir /tmp/foo ; cd /tmp/foo ; shutit skeleton

# Input a new directory name for this module.
# Default: /tmp/shutit_nikeno



# Input module name.
# Default: shutit_nikeno



# Input a unique domain.
# Default: foo.shutit_nikeno



# Input a delivery method from: ('docker', 'dockerfile', 'ssh', 'bash').
# Default: bash

docker = build within a docker image
dockerfile = call "shutit build" from within a dockerfile
ssh = ssh to target and build
bash = run commands directly within bash


Traceback (most recent call last):
  File "/Users/garth/Library//Python/2.7/bin/shutit", line 11, in <module>
    sys.exit(main())
  File "/Users/garth/Library/Python/2.7/lib/python/site-packages/shutit_main.py", line 858, in main
    shutit_util.create_skeleton(shutit)
  File "/Users/garth/Library/Python/2.7/lib/python/site-packages/shutit_util.py", line 1470, in create_skeleton
    templatemodule = open(find_asset('shutit_module_template_bare.py')).read()
IOError: [Errno 2] No such file or directory: 'shutit_module_template_bare.py'
```

**Comment by ianmiell** [comment]
Repro'd - previous repors were stymied by the PATH getting confused with my git checkout:

```
imiell@Ians-Air:~$ shutit skeleton

# Input a new directory name for this module.
# Default: /tmp/shutit_agreed



# Input module name.
# Default: shutit_agreed



# Input a unique domain.
# Default: imiell.shutit_agreed



# Input a delivery method from: ('docker', 'dockerfile', 'ssh', 'bash').
# Default: bash

docker = build within a docker image
dockerfile = call "shutit build" from within a dockerfile
ssh = ssh to target and build
bash = run commands directly within bash


Traceback (most recent call last):
  File "/Users/imiell/Library/Python/2.7/bin/shutit", line 11, in <module>
    sys.exit(main())
  File "/Users/imiell/Library/Python/2.7/lib/python/site-packages/shutit_main.py", line 858, in main
    shutit_util.create_skeleton(shutit)
  File "/Users/imiell/Library/Python/2.7/lib/python/site-packages/shutit_util.py", line 1470, in create_skeleton
    templatemodule = open(find_asset('shutit_module_template_bare.py')).read()
IOError: [Errno 2] No such file or directory: 'shutit_module_template_bare.py'
imiell@Ians-Air:~$ 
```

**Comment by ianmiell** [comment]
Interesting - assets end up here, not in ./Library/Python/2.7/lib/python/site-packages/
```
./Library/Python/2.7/shutit_assets/shutit_module_template_bare.py
./Library/Python/2.7/shutit_assets/shutit_module_template_bare.pyc
```

**Comment by ianmiell** [comment]
Refactoring some code before attempting a change, running tests.

**Comment by ianmiell** [comment]
OK, looks like fixed on my Mac:

```
imiell@Ians-MacBook-Air:~$ PATH=$PATH:/Users/imiell/Library/Python/2.7/bin
imiell@Ians-MacBook-Air:~$ shutit skeleton

# Input a new directory name for this module.
# Default: /tmp/shutit_aminic



# Input module name.
# Default: shutit_aminic



# Input a unique domain.
# Default: imiell.shutit_aminic



# Input a delivery method from: ('docker', 'dockerfile', 'ssh', 'bash').
# Default: bash

docker = build within a docker image
dockerfile = call "shutit build" from within a dockerfile
ssh = ssh to target and build
bash = run commands directly within bash


================================================================================
Run:

	cd /tmp/shutit_aminic/bin && ./build.sh

to build.

An image called shutit_aminic will be created
and can be run with the run.sh command in bin/.
================================================================================
imiell@Ians-MacBook-Air:~$ 
```

**Comment by ianmiell** [comment]
Garth,

Thanks again for persisting with this. It's much appreciated.

I believe I repro'd and fixed, and the code is improved as a result.

Again, please let me know how you get on.

Ian

**Comment by ianmiell** [comment]
Friend who had similar issues on a Mac confirms working now.

**Comment by ianmiell** [comment]
Garth, are you able to confirm this is working?

**Comment by ianmiell** [comment]
Assuming working, closing.
