### ISSUE TITLE
Shut skeleton is failing

### ISSUE THREAD

**Issue by danceasarxx** [ianmiell/shutit#261]
I was following the quick setup guide on [your website](http://ianmiell.github.io/shutit/).
So I installed shutit in a python `2.7.9` environment. On running `shutit skeleton` I get this.

```
# ShutIt Started... 
Traceback (most recent call last):
  File "/home/arewa/.pyenv/versions/gserver-env/bin/shutit", line 9, in <module>
    load_entry_point('shutit==0.9.193', 'console_scripts', 'shutit')()
  File "/home/arewa/.pyenv/versions/2.7.9/envs/gserver-env/lib/python2.7/site-packages/shutit_main.py", line 517, in main
    shutit_util.parse_args()
  File "/home/arewa/.pyenv/versions/2.7.9/envs/gserver-env/lib/python2.7/site-packages/shutit_util.py", line 575, in parse_args
    default_dir = shutit.host['calling_path'] + '/shutit_' + random_word()
  File "/home/arewa/.pyenv/versions/2.7.9/envs/gserver-env/lib/python2.7/site-packages/shutit_util.py", line 207, in random_word
    words = open(word_file).read().splitlines()
IOError: [Errno 2] No such file or directory: 'words'
```

**Comment by ianmiell** [comment]
Thanks for letting me know!
I've now tested and fixed. Please upgrade, eg:

[sudo] pip install --upgrade --force --no-cache shutit

**Comment by danceasarxx** [comment]
Thanks...it's working
