### ISSUE TITLE
Can't install using pip with Python 2.7, OSX

### ISSUE THREAD

**Issue by JasonKeirstead** [ianmiell/shutit#263]
Running as root user, I can't install shutit. 

--

```
pip install --upgrade --force-reinstall shutit
Collecting shutit
  Using cached shutit-0.9.211-py2-none-any.whl
Collecting pexpect>=4.0 (from shutit)
  Using cached pexpect-4.2.1-py2.py3-none-any.whl
Collecting texttable>=0.1 (from shutit)
Collecting jinja2>=0.1 (from shutit)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting pynsca>=1.5 (from shutit)
Collecting ptyprocess>=0.5 (from pexpect>=4.0->shutit)
  Using cached ptyprocess-0.5.1-py2.py3-none-any.whl
Collecting MarkupSafe (from jinja2>=0.1->shutit)
Installing collected packages: ptyprocess, pexpect, texttable, MarkupSafe, jinja2, pynsca, shutit
  Found existing installation: ptyprocess 0.5.1
    Uninstalling ptyprocess-0.5.1:
      Successfully uninstalled ptyprocess-0.5.1
  Found existing installation: pexpect 4.2.1
    Uninstalling pexpect-4.2.1:
      Successfully uninstalled pexpect-4.2.1
  Found existing installation: texttable 0.8.4
    Uninstalling texttable-0.8.4:
      Successfully uninstalled texttable-0.8.4
  Found existing installation: MarkupSafe 0.23
    Uninstalling MarkupSafe-0.23:
      Successfully uninstalled MarkupSafe-0.23
  Found existing installation: Jinja2 2.8
    Uninstalling Jinja2-2.8:
      Successfully uninstalled Jinja2-2.8
  Found existing installation: pynsca 1.5
    Uninstalling pynsca-1.5:
      Successfully uninstalled pynsca-1.5
  Found existing installation: shutit 0.9.211
    Uninstalling shutit-0.9.211:
      Successfully uninstalled shutit-0.9.211
  Rolling back uninstall of shutit
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 378, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/shutit_assets'
```

**Comment by ianmiell** [comment]
Hi, I have no way to test this myself, but have made a change and pushed which may help (v0.9.213).

Failing that, uninstall and try installing as a normal user perhaps? I'm not expert at pip/OSX, but I tend to run pip without sudo as it requires me to.

**Comment by ianmiell** [comment]
Closing, assumed fixed.
