### ISSUE TITLE
list_deps - in bash script context always choosing docker?

### ISSUE THREAD

**Issue by ianmiell** [ianmiell/shutit#289]
```
imiell@rothko:/space/git/shutit-cookbook-openshift3-test (master)$ shutit list_deps
# ShutIt Started... 
# Loading configs...
2017-01-09 14:17:42,178 INFO: ShutIt modules loaded
2017-01-09 14:17:42,191 INFO: Configuration loaded
2017-01-09 14:17:42,191 INFO: Startup command is: docker run --cidfile=/tmp/shutit_imiell/rothko_imiell_1483971461.75.745200/cidfiles/imiell_cidfile_rothko_imiell_1483971461.75.745200 -t -i ubuntu:14.04 /bin/bash
2017-01-09 14:17:42,192 INFO: Downloading image, please be patient
2017-01-09 14:17:56,113 INFO: Sending: PS1='ro''thko:ORIGIN_ENV:EV2ihpc3# '
2017-01-09 14:17:56,165 INFO: Output (squashed): rothko:ORIGIN_ENV:EV2ihpc3# 
2017-01-09 14:17:58,061 INFO: Sending: PS1='2c''fcb6ec0071:root:0lnDbXoy# '
2017-01-09 14:17:58,112 INFO: Output (squashed): 2cfcb6ec0071:root:0lnDbXoy# 
2017-01-09 14:17:59,780 INFO: Connected to target
Traceback (most recent call last):
  File "/usr/local/bin/shutit", line 9, in <module>
    load_entry_point('shutit==0.9.287', 'console_scripts', 'shutit')()
  File "/usr/local/lib/python2.7/dist-packages/shutit_main.py", line 555, in main
    do_lists(shutit)
  File "/usr/local/lib/python2.7/dist-packages/shutit_main.py", line 589, in do_lists
    digraph += '\n'.join([ make_dep_graph(module) for module_id, module in shutit.shutit_map.items() if module_id in cfg and cfg[module_id]['shutit.core.module.build'] ])
NameError: global name 'cfg' is not defined
```

**Comment by ianmiell** [comment]
Fixing.
