### ISSUE TITLE
assert sim is not None

### ISSUE THREAD

**Issue by littleJava** [ianmiell/shutit#308]
what should i do for this issue:

python version is 
```
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
os is mac

just run the `python example.py`
```
##example.py

import shutit
session = shutit.create_session('bash')
session.send('echo Hello World', echo=True)
```
thie output :

```
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import shutit
  File "/Library/Python/2.7/site-packages/shutit.py", line 30, in <module>
    import shutit_global
  File "/Library/Python/2.7/site-packages/shutit_global.py", line 40, in <module>
    from shutit_class import ShutIt, ShutItInit
  File "/Library/Python/2.7/site-packages/shutit_class.py", line 41, in <module>
    from shutit_module import ShutItFailException, ShutItModule
  File "/Library/Python/2.7/site-packages/shutit_module.py", line 101, in <module>
    class ShutItModule(with_metaclass(ShutItMeta)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Library/Python/2.7/site-packages/shutit_module.py", line 78, in __new__
    assert sim is not None
AssertionError
```

**Comment by ianmiell** [comment]
This is a strange one. That assert should never be triggered, and your versions look ok.

Can you run a 'pip list'?

Can you repro in a docker container?

**Comment by ianmiell** [comment]
No response, closing.
