### ISSUE TITLE
Repository handling with serve mode

### ISSUE THREAD

**Issue by zwischenzugs** [ianmiell/shutit#38]
Need a better way to handle this, as when we do serve mode we are not in the root dir (ie could be anywhere), Therefore relative 

Repro: try building win2048 in serve mode:

SHUTIT_ROOT#F8zOA>Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/space/git/shutit/shutit_srv.py", line 45, in build_shutit
    shutit_main.do_build(shutit)
  File "/space/git/shutit/shutit_main.py", line 366, in do_build
    build_module(shutit, module)
  File "/space/git/shutit/shutit_main.py", line 323, in build_module
    if not module.build(shutit):
  File "/space/git/shutit/shutit_module.py", line 42, in wrapper
    ret = func(self, shutit)
  File "library/win2048/win2048.py", line 34, in build
    shutit.send_file('/root/start_win2048.sh',file.read(file('resources/start_win2048.sh')))
IOError: [Errno 2] No such file or directory: 'resources/start_win2048.sh'

Also, the error was not reported on the FE.

**Comment by ianmiell** [comment]
No longer relevant.
